config/routes.rb
Rails.application.routes.draw do
  get 'profiles/index'
  get "home/about"
  get "posts/myposts"
  root "posts#index"


  resources :posts do
    resources :likes, only: [:index]
  end

  resources :comments
  resources :likes, only: [:create, :destroy]

  devise_scope :user do
    get "/users/sign_up", to: "devise/registrations#new"
    get "/users/sign_out", to: "devise/sessions#destroy"
  end
  devise_for :users, controllers: {
    registrations: "users/registrations",
  }
  resources :users

  post 'users/:id/follow', to: "users#follow", as: "follow"
  post 'users/:id/unfollow', to: "users#unfollow", as: "unfollow"
  post 'users/:id/accept', to: "users#accept", as: "accept"
  post 'users/:id/decline', to: "users#decline", as: "decline"
  post 'users/:id/cancel', to: "users#cancel", as: "cancel"
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  validates :text, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]

  # GET /comments or /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to comment_url(@comment), notice: "Comment was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to comment_url(@comment), notice: "Comment was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url, notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_comment
    @comment = Comment.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def comment_params
    params.require(:comment).permit(:text, :user_id, :post_id)
  end
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>" class="post-container">

  <p>
    <strong>Text:</strong>
    <%= comment.text %>
  </p>

  <p>
    <strong>User:</strong>
    <%= comment.user_id %>
  </p>

  <p>
    <strong>Post:</strong>
    <%= comment.post_id %>
  </p>
  <p>
    <%= link_to "", comment, class: "post-link" %>
  </p>
</div>

app/views/comments/_form.html.erb
<div class="col-xl-12 col-md-12 col-sm-12 col-12 post-container">
  <%= form_with(model: comment) do |form| %>
    <% if comment.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

        <ul>
          <% comment.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="col-12">
      <%= form.label :comment, style: "display: block" %>
      <%= form.text_area :text, class: "form-control" %>
    </div>

    <div>
      <%= form.text_field :user_id, type: "hidden" %>
    </div>

    <div>
      <%= form.text_field :post_id, type: "hidden" %>
    </div>

    <div style="margin-top: 10px">
      <%= form.submit class: "btn btn-success col-12" %>
    </div>
  <% end %>
</div>

app/views/comments/edit.html.erb
<h1 style="text-align: center; margin-top: 20px;">Editing comment</h1>
<%= render "form", comment: @comment %>
<br>
<div style="margin-left: 20px; text-align: center;">
  <%= link_to "Show this comment", @comment, class: "btn btn-success col-8" %>

  <%= link_to "Back to comments", comments_path, class: "btn btn-secondary col-8" , style: "margin-top: 10px;"%>
</div>

app/views/comments/index.html.erb
<p style="color: green"><%= notice %></p>

<div style="margin-left: 10px">
  <h1 style="margin-left: 10px;">Comments</h1>
</div>

<div id="comments">
  <% @comments.each do |comment| %>
    <%= render comment %>
  <% end %>
</div>

app/views/comments/new.html.erb
<h1 style="text-align: center; margin-top: 20px;">New comment</h1>
<%= render "form", comment: @comment %>
<br>
<div style="margin-left: 20px; text-align: center;">
  <%= link_to "Show this comment", @comment, class: "btn btn-success col-8" %>

  <%= link_to "Back to comments", comments_path, class: "btn btn-secondary col-8" , style: "margin-top: 10px;"%>
</div>

app/views/comments/show.html.erb
<div class="post-container">

  <p style="color: green"><%= notice %></p>

  <%= render @comment, class: "col-12" %>

  <div >
    <%= link_to "Edit this comment", edit_comment_path(@comment), class: "btn btn-success col-12" %>
    <%= button_to "Destroy this comment", @comment, method: :delete, class: "btn btn-danger col-12", style: "margin-top: 10px;" %>
    <%= link_to "Back to comments", comments_path, class: "btn btn-secondary col-12", style: "margin-top: 10px;" %>
  </div>

</div>