config/routes.rb
Rails.application.routes.draw do
  get 'profiles/index'
  get "home/about"
  get "posts/myposts"
  root "posts#index"


  resources :posts do
    resources :likes, only: [:index]
  end

  resources :comments
  resources :likes, only: [:create, :destroy]

  devise_scope :user do
    get "/users/sign_up", to: "devise/registrations#new"
    get "/users/sign_out", to: "devise/sessions#destroy"
  end
  devise_for :users, controllers: {
    registrations: "users/registrations",
  }
  resources :users

  post 'users/:id/follow', to: "users#follow", as: "follow"
  post 'users/:id/unfollow', to: "users#unfollow", as: "unfollow"
  post 'users/:id/accept', to: "users#accept", as: "accept"
  post 'users/:id/decline', to: "users#decline", as: "decline"
  post 'users/:id/cancel', to: "users#cancel", as: "cancel"
end

app/models/user.rb
class User < ApplicationRecord
  extend Devise::Models
  before_create :generate_token
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  validates :username, presence: true, length: { minimum: 4, maximum: 20 }

  has_many :posts, foreign_key: :user_id, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_one :avatar, dependent: :destroy
  accepts_nested_attributes_for :avatar, allow_destroy: true

  followability

  enum role: { user: 0, admin: 1 }, _default: :user

  def admin?
    role == 'admin'
  end

  def unfollow(user)
    followerable_relationships.where(followable_id: user.id).destroy_all
  end

  def generate_token
    self.token = "#{id}/#{SecureRandom.urlsafe_base64(nil, false)}"
  end

  def self.ransackable_attributes(auth_object = nil)
    super + %w[bio created_at email id remember_created_at reset_password_sent_at reset_password_token token updated_at username]
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  protect_from_forgery with: :null_session

  include Attachable

  def create
    build_resource(sign_up_params)
    resource_saved = resource.save

    yield resource if block_given?

    if resource_saved
      if resource.active_for_authentication?
        upload_avatar(params, resource) if params[:user][:avatar].present?
        set_flash_message :notice, :signed_up if is_flashing_format?
        sign_up(resource_name, resource)
        respond_with resource, location: after_sign_up_path_for(resource)
      else
        set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_flashing_format?
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      @validatable = devise_mapping.validatable?
      if @validatable
        @minimum_password_length = resource_class.password_length.min
      end
      respond_with resource
    end
  end

  def update
    self.resource = resource_class.to_adapter.get!(send(:"current_#{resource_name}").to_key)
  
    if update_resource(resource, update_params)
      upload_avatar(params, resource) if params[:user][:avatar].present?
      set_flash_message :notice, :updated if is_flashing_format?
      bypass_sign_in resource, scope: resource_name
      respond_with resource, location: after_update_path_for(resource)
    else
      clean_up_passwords resource
      set_minimum_password_length
      respond_with resource
    end
  end

  protected

  def sign_up_params
    params.require(:user).permit(:email, :password, :password_confirmation, :bio, :username, :token, :role, avatar_attributes: [ :raw_response, :avatar_id, :avatar_type, :avatar_url ] )
  end

  def update_params
    params.require(:user).permit(:email, :token, :password, :password_confirmation, :current_password, :bio, :username, :role, avatar_attributes: [:raw_response, :avatar_id, :avatar_type, :avatar_url])
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  protect_from_forgery with: :null_session

  def create
    warden.authenticate!(scope: resource_name, recall: "#{controller_path}#new")
    current_user.generate_token
    current_user.save
    current_user.reload
    render json: { user: current_user, status: :ok }
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :destroy, :follow, :unfollow, :accept, :decline, :cancel]
  before_action :authenticate_user!

  def index
    @users = search.where.not(id: current_user.id)
  end

  def show; end

  def follow
    current_user.send_follow_request_to(@user)
    @user.accept_follow_request_of(current_user)
    redirect_to user_path(@user)
  end

  def unfollow
    current_user.unfollow(@user)
    redirect_to user_path(@user)
  end

  def accept
    current_user.accept_follow_request_of(@user)
    redirect_to user_path(@user)
  end

  def decline
    current_user.decline_follow_request_of(@user)
    redirect_to user_path(@user)
  end

  def cancel
    current_user.remove_follow_request_for(@user)
    redirect_to user_path(@user)
  end

  def destroy
    respond_to do |format|
      if current_user.admin?
        @user.destroy
        format.html { redirect_to users_path, alert: "User deleted." }
      else
        format.html { redirect_to users_path, alert: "You don't have permission to do that." }
      end
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def search
    @query = User.ransack(username_cont: search_query)
    @users = @query.result(distinct: true)
  end

  def search_query
    params[:query]
  end
end

app/views/users/_table.html.erb
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<div class="col-14">
  <div class="main-box clearfix">
    <div class="table-responsive">
      <table class="table user-list">
        <thead>
        <tr>
          <th><span>User</span></th>
          <th><span>Created</span></th>
          <th><span>Email</span></th>
        </tr>
        </thead>
        <tbody>
        <% @users.each do |user| %>
          <tr>
            <td class="post-link ">
              <%= link_to(user, class: "post-link username") do%>
                <% if user.avatar.nil?%>
                  <img src="https://i.imgur.com/9nMvJ1e.png" class="rounded-circle" style="width: 50px; height: 50px; object-fit: cover;"/>
                <% else %>
                  <img src="<%= user.avatar.avatar_url %>" class="rounded-circle" style="width: 50px; height: 50px; object-fit: cover;"/>
                <% end %>
                  <h5 class="nav-link text-dark">
                    <strong><%= user.username %></strong>
                  </h5>
              <% end %>
            </td>
            <td>
              <%= user.created_at %>
            </td>
            <td>
             <strong class="text-primary"><%= user.email %></strong>
            </td>
            <td style="width: 20%;">
              <% if current_user.admin? %>
                <%= button_to(user, data: { confirm: "Are you sure?", turbo_confirm: "Are you sure?" }, method: :delete, class: "btn btn-outline-danger") do %>
                  <i class="fa fa-trash"></i>
                  <span class="ms-1 d-none d-sm-inline"><strong>Delete User</strong></span>
                <% end %>
              <% end %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/_user.html.erb
<div class="row">
  <div class="col-12 text-center" style="padding: 20px; background-color: #f2f2f2;">

    <div class="post-link">
      <%= link_to(user, class: "post-link") do %>
         <% if user.avatar.nil?%>
            <img src="https://i.imgur.com/9nMvJ1e.png" class="rounded-circle" style="width: 160px; height: 160px; object-fit: cover;"/>
          <% else %>
            <img src="<%= user.avatar.avatar_url %>" class="rounded-circle" style="width: 160px; height: 160px; object-fit: cover;"/>
          <% end %>
      <% end %>
    </div>

    <div class="post-link">
      <%= link_to(user, class: "text-dark post-link", style: "text-decoration: none;") do %>
        <h4 style="margin-top: 10px;">
          <%= user.username %>
        </h4>
      <% end %>
    </div>
    <div>
    </div>
    <h6> <%= user.followers.count %> Followers </h6>
    <h6> <%= user.following.count %> Following </h6>
    <% if user_signed_in? %>
      <% if current_user.following?(user) %>
        <%= button_to "Unfollow", unfollow_path(user), class: "btn btn-outline-danger" %>
      <% elsif current_user.sent_follow_request_to?(user) %>
        <%= button_to "Cancel follow request", cancel_path(user), class: "btn btn-outline-danger" %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<br>
<div style="margin: 20px;">
  <%= form_with url: profiles_index_path, method: :get do |form| %>
    <%= form.search_field :query, value: params[:query], placeholder: "Search user..", class: "form-control form-control-lg" %>
    <br>
    <%= form.submit "Search", class: "btn btn-primary col-12" %>
  <% end %>
</div>

<% if !@query.nil? %>
<% else %>
  <% if !@users[0].present? %>
    <div class="alert alert-warning" role="alert">
      <h3>
        No Users found!
      </h3>
    </div>
  <% else %>
    <div class="text-center">
      <% @users.each do |user| %>
        <%= render user %>
      <% end %>
    </div>
  <% end %>
<% end %>

<div style="margin: 20px;">
  <h3> All Users </h3>

  <% unless @users.empty? %>
    <%= render 'table' %>
  <% else %>
    <div class="alert alert-warning" role="alert">
      <h2>
        No users found!
      </h2>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-12 text-center" style="padding: 20px; background-color: #f2f2f2;">
    <% if @user.avatar.nil?%>
        <img src="https://i.imgur.com/9nMvJ1e.png" class="rounded-circle" style="width: 160px; height: 160px; object-fit: cover;"/>
    <% else %>
        <img src="<%= @user.avatar.avatar_url %>" class="rounded-circle" style="width: 160px; height: 160px; object-fit: cover;"/>
    <% end %>
    <br>
    <h1> <%= @user.username %> </h1>
    <h5> <%= @user.email %> </h5>
    <h5> <%= @user.bio %> </h5>
    <% if current_user.following?(@user) %>
      <%= button_to "Unfollow", unfollow_path(@user), class: "btn btn-outline-danger" %>
    <% elsif current_user.sent_follow_request_to?(@user) %>
      <%= button_to "Cancel follow request", cancel_path(@user) %>
    <% else %>
      <% if @user.id == current_user.id %>
        <%= link_to "Edit Profile", edit_user_registration_path, class: "btn btn-outline-primary" %>
      <% else %>
        <%= button_to "Follow", follow_path(@user), class: "btn btn-outline-primary" %>
      <% end %>
    <% end %>

    <% unless @user.followers.empty? %>
      <hr>
      <h3 style="text-align: left">Followers</h3>
      <% @user.followers.each do |follower| %>
        <%= render follower %>
        <hr>
      <% end %>
    <% end %>
  </div>
</div>