config/routes.rb
Rails.application.routes.draw do
  get 'profiles/index'
  get "home/about"
  get "posts/myposts"
  root "posts#index"


  resources :posts do
    resources :likes, only: [:index]
  end

  resources :comments
  resources :likes, only: [:create, :destroy]

  devise_scope :user do
    get "/users/sign_up", to: "devise/registrations#new"
    get "/users/sign_out", to: "devise/sessions#destroy"
  end
  devise_for :users, controllers: {
    registrations: "users/registrations",
  }
  resources :users

  post 'users/:id/follow', to: "users#follow", as: "follow"
  post 'users/:id/unfollow', to: "users#unfollow", as: "unfollow"
  post 'users/:id/accept', to: "users#accept", as: "accept"
  post 'users/:id/decline', to: "users#decline", as: "decline"
  post 'users/:id/cancel', to: "users#cancel", as: "cancel"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  validates :title, presence: true, length: { minimum: 5, maximum: 100 }
  validates :description, presence: true, length: { minimum: 5, maximum: 500 }
  validates :keywords, presence: true, length: { minimum: 5, maximum: 100 }

  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :attachments, dependent: :destroy
  accepts_nested_attributes_for :attachments

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index show]

  include Attachable

  # GET /posts or /posts.json
  def index
    @posts = Post.includes(:user, :likes).order(id: :desc).all
  end

  def myposts
    @posts = Post.includes(:user, :likes).order(id: :desc).where(user_id: current_user.id)
  end

  # GET /posts/1 or /posts/1.json
  def show
    @comment = @post.comments.build
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit; end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    respond_to do |format|
      if @post.save
        upload_attachments(params, @post) if params[:post][:attachment].present?
        format.html { redirect_to post_url(@post), notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        @post.attachments.destroy_all
        upload_attachments(params, @post) if params[:post][:attachment].present?
        format.html { redirect_to post_url(@post), notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:title, :description, :keywords, :user_id)
  end
end

app/views/posts/_form.html.erb
<div class="col-xl-5 post-container">
  <%= form_with(model: post) do |form| %>
    <div>
      <% invalid = post.errors.include?(:title) %>
      <%= form.label :title, style: "display: block" %>
      <%= form.text_field :title, class: "form-control" %>
      <% if invalid %>
        <p style="color:red">
          <%= post.errors.full_messages_for(:title).join(" ,") %>
        </p>
      <% end %>
    </div>
    <div>
      <%= form.text_field :user_id, type: "hidden", value: current_user.id %>
    </div>
    <div>
      <% invalid = post.errors.include?(:description) %>
      <%= form.label :description, style: "display: block" %>
      <%= form.text_area :description, class: "form-control" %>
      <% if invalid %>
        <p style="color:red">
          <%= post.errors.full_messages_for(:description).join(" ,") %>
        </p>
      <% end %>
    </div>
    <div>
      <% invalid = post.errors.include?(:keywords) %>
      <%= form.label :keywords, style: "display: block" %>
      <%= form.text_field :keywords, class: "form-control" %>
      <% if invalid %>
        <p style="color:red">
          <%= post.errors.full_messages_for(:keywords).join(" ,") %>
        </p>
      <% end %>
    </div>
    <br>
    <div>
      <%= form.label :add_photo_or_more, style: "display: block" %>
      <%= form.file_field :attachment, multiple: true %>
    </div>
    <br>
    <div>
      <%= form.submit class: "btn btn-primary col-12" %>
    </div>
  <% end %>
</div>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>" class="post-container">
  <%= link_to(post.user, class: 'nav-link post-link', style: "text-align: left;") do %>
    <% if post.user.avatar.nil? %>
      <%= image_tag "https://i.imgur.com/9nMvJ1e.png", class: "rounded-circle", width: "45", height: "45", loading: 'lazy', style: "object-fit: cover;" %>
    <% else %>
      <%= image_tag post.user.avatar.avatar_url, class: 'rounded-circle', width: '40', height: '40', loading: 'lazy', style: "object-fit: cover;" %>
    <% end %>
    <span class="d-none d-sm-inline mx-1 text-dark"><strong><%= post.user.username %></strong></span>
  <% end %>
  <br>
  <%= link_to(post_path(post.id), class: "post-link text-dark") do %>
    <div class="post-title">
      <%= post.title %>
    </div>
  <% end %>
  <br>
  <%= link_to(post_path(post.id), class: "post-link") do %>
    <% if post.attachments.count > 1 %>
      <div class="image-container">
        <% post.attachments.each do |image| %>
          <img src="<%= image.resource_url %>" class="rounded" loading="lazy"/>
        <% end %>
      </div>
    <%else%>
      <% post.attachments.each do |image| %>
          <img src="<%= image.resource_url %>" class="rounded" style="max-width: 100%" loading="lazy"/>
      <% end %>
    <% end %>
  <% end %>
  <div style="margin-top: 10px;" class="text-center">
    <% if user_signed_in? %>
      <% like = current_user.likes.find_by(post: post) %>
      <% if like.nil? %>
        <%= button_to "", likes_path, params: { like: { post_id: post.id } }, class: "like", method: :post %>
      <% else %>
        <%= button_to "", like_path(like), class: "unlike", method: :delete %>
      <% end %>
    <% end %>
    <%= link_to(post_likes_path(post), class: "post-link") do %>
      <h6 class="text-primary">
        <%= post.likes.count %> Likes
      </h6>
    <% end %>
  </div>
</div>

app/views/posts/edit.html.erb
<h1 style="text-align: center; margin-top: 20px;">Editing post</h1>
<%= render "form", post: @post %>
<br>
<div style="margin-left: 20px; text-align: center;">
  <%= link_to "Show this post", @post, class: "btn btn-success col-2" %>
  <%= link_to "Back to posts", posts_path, class: "btn btn-secondary col-2" %>
</div>

app/views/posts/index.html.erb
<%= stylesheet_link_tag("post") %>
<p style="color: green"><%= notice %></p>

<% if !@posts.empty? %>
  <div id="posts" class="text-center">
    <% @posts.each do |post| %>
      <%= render post %>
    <% end %>
  </div>
  <%else%>
  <div id="posts" class="text-center">
    <h3 class="alert alert-warning">There are no posts to show</h3>
      <%= link_to(new_post_path, class: "btn btn-primary btn-lg") do %>
        <i class="fa fa-plus-circle"></i>
        <span class="ms-1 d-none d-sm-inline"><strong>Create Post</strong></span>
      <% end %>
  </div>
<% end %>

app/views/posts/myposts.html.erb
<%= stylesheet_link_tag("post") %>
<p style="color: green"><%= notice %></p>

<% if !@posts.empty? %>
  <div id="posts" class="text-center">
    <% @posts.each do |post| %>
      <%= render post %>
    <% end %>
  </div>
  <%else%>
  <div id="posts" class="text-center">
    <h3 class="alert alert-warning">There are no posts to show</h3>
      <%= link_to(new_post_path, class: "btn btn-primary btn-lg") do %>
        <i class="fa fa-plus-circle"></i>
        <span class="ms-1 d-none d-sm-inline"><strong>Create Post</strong></span>
      <% end %>
  </div>
<% end %>

app/views/posts/new.html.erb
<div style="margin-top: 10px;">
  <h1 style="text-align: center;">Create post</h1>
  <%= render "form", post: @post %>
</div>

<br>

<div style="text-align: center;">
  <%= link_to "Back to posts", posts_path, class: "btn btn-secondary col-5" %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>
<%= render "comments/form", comment: @comment %>

<div class="post-container">
  <% if user_signed_in? %>
    <% if current_user.id == @post.user.id || current_user.admin? %>
      <%= link_to "Edit this post", edit_post_path(@post), class: "btn btn-success col-12" %>
      <%= button_to "Delete this post", @post, method: :delete, class: "btn btn-danger col-12", style: "margin-top: 10px;" %>
    <% end %>
  <% end %>
  <%= link_to "Back to posts", posts_path, class: "btn btn-secondary col-12", style: "margin-top: 10px;" %>
</div>

<div style="margin-top: 10px; text-align: center;">
  <h5>Comments</h5>
  <% @post.comments.each do |comment| %>
    <h6><%= comment.text %></h6>
  <% end %>
</div>